# Generated by Django 5.1.3 on 2025-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
    ]
