# Generated by Django 5.1.3 on 2025-01-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymApp', '0002_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloque',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='bloque',
            name='fecha_inicio',
        ),
    ]
